/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        background: '#fbf9f1',
        'secondary-fixed': '#ffdbd0',
        'on-tertiary-fixed': '#320047',
        'on-secondary': '#ffffff',
        'surface-dim': '#dcdad2',
        'primary-fixed': '#ffdbcd',
        'on-tertiary-fixed-variant': '#6c228c',
        'secondary-container': '#fed4c8',
        'surface-container': '#f0eee6',
        'on-tertiary': '#ffffff',
        'surface-tint': '#a23f00',
        'on-secondary-fixed-variant': '#5d4037',
        'inverse-primary': '#ffb595',
        'outline-variant': '#e0c0b2',
        'surface-container-low': '#f5f4ec',
        'on-error': '#ffffff',
        'on-primary': '#ffffff',
        'surface-bright': '#fbf9f1',
        'on-background': '#1b1c17',
        'on-error-container': '#93000a',
        'surface-variant': '#e4e3db',
        'on-primary-fixed': '#351000',
        error: '#ba1a1a',
        'on-tertiary-container': '#fffbff',
        'secondary-fixed-dim': '#e6beb2',
        secondary: '#76574e',
        outline: '#8c7166',
        'on-surface': '#1b1c17',
        'on-surface-variant': '#594238',
        'on-primary-fixed-variant': '#7c2e00',
        'surface-container-high': '#eae8e0',
        'error-container': '#ffdad6',
        'on-secondary-container': '#795950',
        'surface-container-highest': '#e4e3db',
        'tertiary-fixed-dim': '#ecb2ff',
        'surface-container-lowest': '#ffffff',
        'tertiary-fixed': '#f8d8ff',
        'inverse-on-surface': '#f3f1e9',
        'primary-fixed-dim': '#ffb595',
        surface: '#fbf9f1',
        tertiary: '#843ba3',
        'on-secondary-fixed': '#2c160f',
        'primary-container': '#c64f00',
        'tertiary-container': '#a055be',
        'on-primary-container': '#fffbff',
        primary: '#9e3d00',
        'inverse-surface': '#30312c',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      spacing: {
        unit: '8px',
        'container-max': '1200px',
        gutter: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '40px',
        xs: '4px',
        xl: '64px',
        md: '24px',
        base: '8px',
        sm: '12px',
        lg: '40px',
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg-mobile': [
          '28px',
          { lineHeight: '36px', fontWeight: '700' },
        ],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'headline-lg': [
          '32px',
          {
            lineHeight: '40px',
            letterSpacing: '-0.01em',
            fontWeight: '700',
          },
        ],
        'headline-xl': [
          '40px',
          {
            lineHeight: '48px',
            letterSpacing: '-0.02em',
            fontWeight: '700',
          },
        ],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-md': [
          '14px',
          {
            lineHeight: '20px',
            letterSpacing: '0.02em',
            fontWeight: '600',
          },
        ],
      },
      keyframes: {
        gentleBounce: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-8px)' },
        },
        slowPulse: {
          '0%, 100%': { opacity: '0.20', transform: 'scale(1)' },
          '50%': { opacity: '0.35', transform: 'scale(1.05)' },
        },
        fadeInUp: {
          from: { opacity: '0', transform: 'translateY(16px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        'gentle-bounce': 'gentleBounce 3s ease-in-out infinite',
        'slow-pulse-8': 'slowPulse 8s ease-in-out infinite',
        'slow-pulse-10': 'slowPulse 10s ease-in-out infinite',
        'slow-pulse-12': 'slowPulse 12s ease-in-out infinite',
        'slow-pulse-4': 'slowPulse 4s ease-in-out infinite',
        'fade-in-up': 'fadeInUp 0.8s ease-out forwards',
      },
    },
  },
  plugins: [],
};
